### ISSUE TITLE
QSO high tail of z distribution different between mock and mock randoms

### ISSUE THREAD

**Issue by londumas** [igmhub/SaclayMocks#10]
The high tail of the redshift distribution is different between mock QSO and mock random QSO.

![high_tail_z_distrib_QSO](https://user-images.githubusercontent.com/3166436/54295348-71412e80-4578-11e9-880a-ef3f4d9b8732.png)

**Comment by TEtourneau** [comment]
Are you talking about difference between masterRSD and random ? I don't see such difference in your plot.
Is the difference between masterRSD and desiDRQ due to the fact that the assign redshift to a quasar has some incertainties (due to observations) ?

**Comment by jmarclegoff** [comment]
We cannot really see where the blue line is at z > 3.6.
However it looks like masterRSD is cut sharp at z=3.6, while masternoRSD is smooth.
Could it be that the two curves are inverted ?
The random are cut sharp at z = 3.6, which might be they miss the smearing due to velocity.

**Comment by jmarclegoff** [comment]
@londumas could you confirm whether the blue and orange curves are inverted or not, and could you produce a plot that shows only these two curves so that we can see where the blue curve is at z > 3.6 (I suspect it is below the red) ?

**Comment by londumas** [comment]
@jmarclegoff, thanks for the remark. Indeed "masterRSD" and "random" have the same distribution on the tail at high z. Plotting them on different plots is better, they were not inverted, simply overplotted. Closing this issue. Sorry for the noise.

![QSO_master_RSD_high_tail](https://user-images.githubusercontent.com/3166436/54368151-394df000-4639-11e9-86ad-877573d28967.png)

![QSOrand_master_RSD_high_tail](https://user-images.githubusercontent.com/3166436/54368150-394df000-4639-11e9-9742-a9d84aa8454a.png)

**Comment by londumas** [comment]
Just to keep track, the low z tail is ok also:

![QSO_master_RSD_low_tail](https://user-images.githubusercontent.com/3166436/54368523-f3455c00-4639-11e9-8174-fbe9f7a328e6.png)

![QSOrand_master_RSD_low_tail](https://user-images.githubusercontent.com/3166436/54368521-f3455c00-4639-11e9-82e9-f60bccf4f580.png)
