### ISSUE TITLE
QSO autocorrelation decreases too fast with r

### ISSUE THREAD

**Issue by jmarclegoff** [igmhub/SaclayMocks#12]
For r>20 Mpc/h QSO-QSO CF is too low

![Screen Shot 2019-03-12 at 7 41 16 PM](https://user-images.githubusercontent.com/28785007/54372066-e39a3780-467a-11e9-9524-345311613ced.png)

**Comment by jmarclegoff** [comment]
This is likely to be related to the default number of bins in the calculation of the lognormal P(k)
def LogNormalP(k,P,nk=32 x 1024)
![PastedGraphic-4](https://user-images.githubusercontent.com/28785007/54372398-86eb4c80-467b-11e9-8546-989172666225.png)
Increasing nk to def LogNormalP(k,P,nk=1024 x 1024) gives
![PastedGraphic-3](https://user-images.githubusercontent.com/28785007/54372438-9a96b300-467b-11e9-8c02-41897806b5aa.png)
To be checked with a new prod

**Comment by londumas** [comment]
@TEtourneau, could you add the plots you send us by email to this ticket?

**Comment by londumas** [comment]
Looks fixed in v4.2, using 400,000 mock qso and mock random qso.
Sending with 800,000 to confirm.

![autoQSO](https://user-images.githubusercontent.com/3166436/54630005-7bfb3800-4a3e-11e9-9b41-52806f56cade.png)

**Comment by londumas** [comment]
Indeed fixed in v4.2. Here it is for 800,000 mock data and mock randoms.

![auto_QSO](https://user-images.githubusercontent.com/3166436/54637215-b6200600-4a4d-11e9-97a4-e1d44a185091.png)

**Comment by londumas** [comment]
@TEtourneau and @jmarclegoff, thanks! This correlation is very impressively close to the linear theory!
