### ISSUE TITLE
speed of light definition and other constants

### ISSUE THREAD

**Issue by londumas** [igmhub/SaclayMocks#15]
Looking at the code, I have not found any issue with the definition of the speed of light and other constants. I have however found some hard-coded constants. @TEtourneau, could you fix the following:
 -  get all the constants from `py/LyaMocks/Constant.py` in `bin/test3D.py`, for example the speed of light.
 - `lambda_min = 3530.0` in `py/LyaMocks/Constant.py`, since it is a float
 - remove unused `c = 299792.458` at line 55 `py/LyaMocks/Constant.py`, in order not to find it using `grep`.

As I said, I have not found any mistake, only some details. So there is no rush for this issue.

**Comment by TEtourneau** [comment]
The principal hardcoded parameters are now stored in
`py/SaclayMocks/constant.py`
