### ISSUE TITLE
exclusion radius for DLA with respect to background quasar

### ISSUE THREAD

**Issue by londumas** [igmhub/SaclayMocks#2]
Same issue as in https://github.com/igmhub/LyaCoLoRe/issues/40.
We might want an exclusion radius between the host quasar and the DLA.
The distribution of DLA has an unphysical peak near the host quasar, because of the mock cell resolution.

![distribution_vs_lRF](https://user-images.githubusercontent.com/3166436/54291022-8f576080-4571-11e9-86a9-5f90808d99df.png)

**Comment by londumas** [comment]
@TEtourneau, I think that at least there should not be any DLA in the same large scale cell of a QSO? How big is that in Mph/h and in km/s?

**Comment by TEtourneau** [comment]
The voxcells are (2.19 Mpc/h)^3 (used for the large scale field).
There is a condition in the code to draw a DLA, which is zmin < z_dla < z_qso.
I can add something to prevent drawing DLA in the same voxcell.

I was also thinking about adding a negative term in the probability of drawing a DLA: 
P += - exp(-r^2 / r_exclusion^2)
in order to reproduce the distribution of the data.

**Comment by londumas** [comment]
@TEtourneau, Indeed the condition should be something like: `zmin < z_dla < z_qso-dz_cell`.
However, let's not aim at reproducing exactly the data, there are a lot of selection effect in the data that are not good. I would not add this function for now: `P += - exp(-r^2 / r_exclusion^2)`.
Maybe with the work of @solenechabanier, we will know better about the data at some point, but for now I don't trust them all the way. Does that sound ok to you @TEtourneau?

**Comment by TEtourneau** [comment]
Yes sure.
So I just add something to prevent drawing a DLA in the same voxcell as a QSO ? Like your dz_cell example ?

**Comment by londumas** [comment]
@TEtourneau, Yes, we don't want basically DLA to be the same as a QSO. Do you agree?

**Comment by TEtourneau** [comment]
Yes totally !

**Comment by TEtourneau** [comment]
I rerun the DLA production, adding this dz cut. I calculated dz to be the redshift difference of 1 voxcell of 2.19Mpc/h:
(dz against z)
![Screen Shot 2019-03-14 at 4 45 39 PM](https://user-images.githubusercontent.com/36950825/54441459-1a388680-473d-11e9-9406-a8691056b49b.png)

here is the new distribution:
![image](https://user-images.githubusercontent.com/36950825/54441496-31777400-473d-11e9-963a-f01f3da84896.png)

So it didn't make the peak disapear. Actually this peak is approximatly 2000km/s large. Which correspond to approximatly 10 cells.
Maybe we want to keep these DLA. It's just that de DLA finder doesn't detect those DLA.
We could try to run the DLA finder on this distribution, to see if we recover the distribution of the data.

**Comment by londumas** [comment]
@TEtourneau, Yes I agree with all of what you said. I is important to cut DLAs in the same cell as a QSO, however, we don't want to match exactly the data distribution. Also we very well know that the DLA are correlated with the quasars. This looks perfect.

**Comment by londumas** [comment]
fixed in v4.2.
![distrib](https://user-images.githubusercontent.com/3166436/54628455-325d1e00-4a3b-11e9-8512-cc6e6056ad89.png)
