### ISSUE TITLE
Distribution of quasar and DLA on the sky is inhomegenous

### ISSUE THREAD

**Issue by londumas** [igmhub/SaclayMocks#21]
Distribution of quasar and DLA on the sky is inhomegenous in `/project/projectdirs/desi/mocks/lya_forest/saclay/v4.4/v4.4.7/`

![QSO](https://user-images.githubusercontent.com/3166436/56598526-e0676500-65b1-11e9-8772-5f31b75cf85e.png)

![DLA_random](https://user-images.githubusercontent.com/3166436/56598527-e0676500-65b1-11e9-9f9f-4d9b75330662.png)

![DLA](https://user-images.githubusercontent.com/3166436/56598528-e0676500-65b1-11e9-9a7a-4370eeeefb03.png)

**Comment by londumas** [comment]
It is ok in `/project/projectdirs/desi/mocks/lya_forest/saclay/v4.4/v4.4.8/` and ok in `/project/projectdirs/desi/mocks/lya_forest/saclay/v4.4/v4.4.9/`. Maybe it is an issue that happen only for `v4.4.7` during the NERSC computation.

**Comment by TEtourneau** [comment]
Ok. I'll rerun the last step of the production, ie generating the catalogs for QSO and DLA for version v4.4.7
We will see if this solves the problem.
(And it will produce the DLA catalog with the good n_HI distribution.)

**Comment by londumas** [comment]
ok, thanks. @TEtourneau tell me when it is ready and I will have a new look.

**Comment by TEtourneau** [comment]
I got the result, the DLA cover the right n_HI range, but there is still this inhomogeneity problem. I think it's due to a bug during the production of 1 of the chunks. I'll need to compute it again.
I'll produce the DLA catalog for version v4.4.8 and v4.4.9, they will be ready in ~ 1 hour
(you can just check if the master_DLA_random.fits has been rewritten)

**Comment by londumas** [comment]
@TEtourneau, yes it must be an issue with the computation on NERSC since even a part of the SGC is missing.

**Comment by londumas** [comment]
Fixed.
