### ISSUE TITLE
absorption smaller than 91.2 nm

### ISSUE THREAD

**Issue by londumas** [igmhub/SaclayMocks#27]
In the SaclayMocks, there are no absorption smaller than 91.2 nm, see the two attached plots.
If I understood correctly this is a feature chosen in order to reduce the size of the box along the line-of-sight. This makes totally sense for all the most important analysis we want to do with Lyman-alpha: BAO, f*sigma8, ...
However, it produces spectra that are not a proper representation of observation for lambda_RF<91.2 nm. If we care about that, I propose two possible fixes:
 - the SaclayMock team can add random Lyman-alpha absorption, following their known or measured PDF and redshift evolution of PDF.
 - the Quickquasar team can add random Lyman-alpha absorption following a given known or measured PDF.

We could also decide, that we do not have to care about that feature, and this is totally fine.
What do you think @TEtourneau, @jmarclegoff and @andreufont et al.?

![var_t_vs_lrf](https://user-images.githubusercontent.com/3166436/57169652-3bc10080-6dc5-11e9-8744-5ad1bd26b3d6.png)

![example_quasar_saclay](https://user-images.githubusercontent.com/3166436/57169653-3bc10080-6dc5-11e9-8d17-3ad560a263d6.png)

**Comment by jmarclegoff** [comment]
@londumas, this is actually already on my todo list. This cut at 91.2 nm was decided with Nicolas a long time ago. Meanwhile the box was extended to start closer to the observer. So I think we will simply remove the cut for the next production. 
I am also planning to include the items of the todo list as github issues.

**Comment by londumas** [comment]
@jmarclegoff, ok sounds good. How far could you go? Would you have enough to cover all the observed wavelength range?
Adding the todo list as github issues sounds like a very good idea. You can label them as "enhemcement".

**Comment by jmarclegoff** [comment]
Actually I now realise that the 91.2 nm (rf) cut was not set to reduce the size of the box along the l.o.s. For low z quasars, just for the lya region, we need a box that goes down to 353 nm (lab). For high z quasars we need to go below 91.2 nm (rf) but will never need below 353 nm (lab). 
Probably we put this 91.2 nm cut to avoid computing the Gaussian averaged field (which takes significant CPU) for pixels that will never be used in the analysis. However these pixels exist only for high z quasars, and there are not so many of them. So, at the end, I believe this cut does not provide a significant CPU reduction. to be checked.

**Comment by londumas** [comment]
@jmarclegoff, then what about measuring the loss in CPU time with a smaller box? Less than 10% is nothing really.

**Comment by TEtourneau** [comment]
The current version of the code does not apply this 91.2 nm (rf) cut anymore.
Here is a plot showing the transmitted flux fraction as a function of lambda rest frame : 
![Screen Shot 2019-09-20 at 12 15 07 PM](https://user-images.githubusercontent.com/36950825/65319675-7a066300-dba0-11e9-927c-9322d2c14c5f.png)
