### ISSUE TITLE
DLA distribution on the sky is not homogenous

### ISSUE THREAD

**Issue by londumas** [igmhub/SaclayMocks#3]
The distribution of DLA, and random DLA on the sky do not follow that of the 
quasars. See plot bellow. Is that linked to the chunks?

![sky_QSO](https://user-images.githubusercontent.com/3166436/54291714-9af75700-4572-11e9-8e1c-8a0c0a013333.png)

![sky_DLA](https://user-images.githubusercontent.com/3166436/54291715-9af75700-4572-11e9-8ce1-654a115869ad.png)

![sky_random_DLA](https://user-images.githubusercontent.com/3166436/54291717-9af75700-4572-11e9-8500-d00903ca5342.png)

**Comment by jmarclegoff** [comment]
This is a good point and a good lead to finding the problem.
Indeed there seem to be a lower density at the edges of the chunks.

**Comment by TEtourneau** [comment]
After some minor bug correction, here is the new distribution, which seems homogeneous:
![image](https://user-images.githubusercontent.com/36950825/54441894-ec077680-473d-11e9-8e4a-4391324930bc.png)
![image](https://user-images.githubusercontent.com/36950825/54441900-ef9afd80-473d-11e9-9850-5dc2fb5482e9.png)

**Comment by londumas** [comment]
fixed in v4.2.
![survey](https://user-images.githubusercontent.com/3166436/54628334-ef9b4600-4a3a-11e9-821f-197261573742.png)
