### ISSUE TITLE
`dist` is not defined.

### ISSUE THREAD

**Issue by londumas** [igmhub/SaclayMocks#37]
`dist` is not defined.
https://github.com/igmhub/SaclayMocks/blob/0ed8fdf24638c5ad38e8f190ad208a5b304aad30/bin/merge_qso.py#L121

**Comment by TEtourneau** [comment]
Sorry for that. I tested it but apparently we don't see if merge_qso or merge_randoms go wrong in the run_mergechunks.log file
I corrected and merged the commits to the master

**Comment by londumas** [comment]
Thanks.
I found the fix to the tests to catch these errors. I will do a PR.

**Comment by londumas** [comment]
fixed.
