### ISSUE TITLE
DLA absorption are not added to the mocks

### ISSUE THREAD

**Issue by londumas** [igmhub/SaclayMocks#5]
DLA absorption are not added to the mocks in `global/projecta/projectdirs/desi/mocks/lya_forest/saclay/v4.1/quick-0.3/`. It might be simply linked to issue https://github.com/igmhub/SaclayMockFeatures/issues/4.
The following plot shows the stack in 1d at the DLA restframe.

![stack_1d_DLA](https://user-images.githubusercontent.com/3166436/54292165-561ff000-4573-11e9-8f41-c088f88c0f0c.png)

**Comment by TEtourneau** [comment]
I corrected issue #4 but didn't run quickquasars yet.
This is something we have to test.

**Comment by londumas** [comment]
Fixed in v4.2.

![fixed_introduced_DLA](https://user-images.githubusercontent.com/3166436/54642828-25502700-4a5b-11e9-9903-5389e2e219b2.png)
