### ISSUE TITLE
Pixel sizes not constant in transmission files

### ISSUE THREAD

**Issue by Waelthus** [igmhub/SaclayMocks#53]
I observed that the pixel sizes of transmission files are not constant, but instead seem to vary between 197 and 203 kpc in a not completely random way (see plots).
I'm not sure if this causes problems for any analysis, but it might be good to figure out where it comes from. 
Code below the figs was used to find the problem.

![reproduce_bug](https://user-images.githubusercontent.com/3012942/60252344-5b0e7280-98ca-11e9-8944-0c59e245faf4.png)

Zoom-in:
![reproduce_bug_zoom](https://user-images.githubusercontent.com/3012942/60252345-5b0e7280-98ca-11e9-9381-012fcf217353.png)

```python
# coding: utf-8
from astropy.cosmology import Planck15
import astropy.constants as c
import astropy.units as u
import astropy.io.fits as fits
from astropy.cosmology import FlatLambdaCDM
import numpy as np

f = fits.open(
    "/project/projectdirs/desi/mocks/lya_forest/develop/saclay/v4.4/v4.4.0/0/0/transmission-16-0.fits.gz"
)
cosmo=FlatLambdaCDM(H0=67.31*u.km/u.s/u.Mpc,Om0=0.31457)  #from header
#cosmo = Planck15


def zoflam(lam):
    return lam / 1215.67 - 1


pixsize_wavelength = np.diff(f["wavelength"].data)
redshifts = zoflam(f["wavelength"].data)
redshifts_recentered = (redshifts[:-1] + redshifts[1:]) / 2
pixsize_in_velscale = np.diff(np.log(f["wavelength"].data)) * c.c
pixsize_in_lengthscale = (
    pixsize_in_velscale / cosmo.H(redshifts_recentered) * (1 + redshifts_recentered)
).to(u.Mpc / cosmo.h)

print(
    "sigma_pixsize/pixsize: {}".format(
        np.std(pixsize_in_lengthscale) / np.mean(pixsize_in_lengthscale)
    )
)
print(
    "max_pixsize: {}, min_pixsize: {}".format(
        np.max(pixsize_in_lengthscale), np.min(pixsize_in_lengthscale)
    )
)
```

pixsize_in_lengthscale array output:
[reproduce_bug.txt](https://github.com/igmhub/SaclayMocks/files/3333767/reproduce_bug.txt)

**Comment by jmarclegoff** [comment]
@Waelthus, I was able to reproduce your plot on a very small production on my laptop. 
I also tried on London v8.0 mocks. The first plot shows that their pixel size is not constant but a zoom exhibits the same kind of structures as observed for Saclay mocks.

![image](https://user-images.githubusercontent.com/28785007/60351817-d8b7a880-99c6-11e9-85d5-3dd2e43cba19.png)

![image](https://user-images.githubusercontent.com/28785007/60351718-a148fc00-99c6-11e9-93ee-5ff8f3a50c86.png)

So I wonder whether this could have to do with the way you compute the pixel size.  
Indeed, computing the pixel size with the code below I get
![image](https://user-images.githubusercontent.com/28785007/60353338-1f5ad200-99ca-11e9-88d3-21a6a954206f.png)

 ````
# coding: utf-8
import astropy.io.fits as fits
import numpy as np
from matplotlib import pyplot as plt
import cosmolopy.distance as dist


f = fits.open("/Users/legoff/ana/SaclayMocks/bin/mocks/128/0/16/1641/transmission-16-1641.fits.gz")

Om=0.31457
OL=1-Om
Ok=0
h=1 # to get results in Mpc/h
cosmo_fid = {'omega_M_0':Om, 'omega_lambda_0':OL, 'omega_k_0':Ok, 'h':h}
R_of_z, z_of_R = dist.quick_distance_function(dist.comoving_distance, return_inverse=True, **cosmo_fid)

def zoflam(lam):
    return lam / 1215.67 - 1

wave = f["wavelength"].data
redshifts = zoflam(wave)
edges = R_of_z(redshifts)
pixsize_in_lengthscale=np.diff(edges)


print("sigma_pixsize/pixsize: {}".format(np.std(pixsize_in_lengthscale) / np.mean(pixsize_in_lengthscale)))
print("max_pixsize: {}, min_pixsize: {}".format(np.max(pixsize_in_lengthscale), np.min(pixsize_in_lengthscale)))
plt.plot(pixsize_in_lengthscale)
plt.show()
```
`

**Comment by jmarclegoff** [comment]
To be more precise, there is still some structure but with an order of magnitude lower amplitude
sigma_pixsize/pixsize: 0.000682920326908
max_pixsize: 0.20046625452, min_pixsize: 0.19950042148
the relative rms is 6.8E-4 instead of 5.3E-3 
Here is a zoomed view at the location where the structure is the largest
![image](https://user-images.githubusercontent.com/28785007/60354629-f2f48500-99cc-11e9-8a20-230da3287d99.png)

**Comment by Waelthus** [comment]
Ok, so my approximation lead to the weird features and computing comoving distances more properly. I wouldn't have guessed that the approximations in my code (which are basically Deltaλ << λ [true on the 8e-5 level] when converting to velocity and assuming for each pixel that the Hubble function is constant within a pixel (true on the ~1e-4 level)) would produce differences that large.

The correct distance calculation just leaves us with mostly random noise on the sub-permille level. I guess that's good enough for all practical purposes.

**Comment by jmarclegoff** [comment]
@Waelthus I agree that this is surprising. 
So I thought maybe the approximation is actually in the R_of_z function, which is an interpolation. Since it is used both in the mocks and in my version of pixel_size.py the approximation may mostly cancel. 
The default interpolation step is dz = 0.001, reducing it to 0.0001 does not change any digit of the output of your pixel_size.py. Increasing it to 0.1 has a tiny effect on the output :
sigma_pixsize/pixsize: 0.00534290634096
sigma_pixsize/pixsize: 0.00533785717562
So I believe the problem is not there.

**Comment by jmarclegoff** [comment]
Also if I apply my version of pixel_size.py to London mocks, the structures are reduced by an order of magnitude relative to what I was getting with yours (I am selecting the same range of lambda as above) 
![image](https://user-images.githubusercontent.com/28785007/60432383-6a5f2a00-9c02-11e9-9587-ef50b668755b.png)

**Comment by Waelthus** [comment]
I double checked the result using astropy.cosmology instead of cosmolpy. The comoving_distance function there does properly perform ∫ E(z)^-1 dz using `scipy.integrate.quad` to get the comoving distance and gives the same result you had.
For the London I didn't check. Might the tilt in pixel size be a slightly different cosmology they use? Or are they using the same one?

Anyway. We know now that it's all okay as long as the pixel size is computed in the right way. As quickquasars interpolates the array to the quasar wavelength grid, there shouldn't be any effects due to these mappings after. For using the transmission files directly one needs to be a bit more careful close to the pixel scales, but even then effects should be minor.
Thanks for looking into it!
