### ISSUE TITLE
beta and growth_rate seem negative

### ISSUE THREAD

**Issue by londumas** [igmhub/SaclayMocks#6]
beta and growth_rate seem negative. It can also be simply an issue with too low statistics, that allows to jump from one local minimum (positive beta) to another (negative beta).
It can not be seen by eye on the correlation function.
```
beta(z=2.45 = -0.221 +/- 0.061
f(z=2.45 = -1.01 +/- 0.31
```

![xi_auto_DLA](https://user-images.githubusercontent.com/3166436/54292465-dcd4cd00-4573-11e9-9c6b-a87e209e799d.png)

![beta_DLA](https://user-images.githubusercontent.com/3166436/54292346-a5662080-4573-11e9-859b-b766ee028d0b.png)

![f_DLA](https://user-images.githubusercontent.com/3166436/54292348-a5feb700-4573-11e9-9786-3df87457001a.png)

**Comment by TEtourneau** [comment]
After the correction I made, I computed the auto correlation of DLA.
Here is a plot:
![image](https://user-images.githubusercontent.com/36950825/54442596-33423700-473f-11e9-9edb-e540ceea7e70.png)
![image](https://user-images.githubusercontent.com/36950825/54442607-376e5480-473f-11e9-9566-a77921de3ff8.png)

We are missing some stats here, but the RSD direction looks good.

**Comment by londumas** [comment]
@TEtourneau, the beta is basically zero in v4.2:
```
------------------------------------------------------------------------------------------------------------
| No |           Name            |  Value   | Sym. Err |   Err-   |   Err+   | Limit-   | Limit+   | Fixed |
------------------------------------------------------------------------------------------------------------
|  0 |                 alpha_DLA | 1.44     | 0        |          |          |          |          |  Yes  |
|  1 |                        ap | 1.02     | 0.217    |          |          | 0.5      | 1.5      |       |
|  2 |                        at | 0.959    | 0.0838   |          |          | 0.5      | 1.5      |       |
|  3 |                   bao_amp | 1        | 0        |          |          |          |          |  Yes  |
|  4 |                  beta_DLA | -0.0349  | 0.0182   |          |          |          |          |       |
|  5 |              bias_eta_DLA | 1        | 0        |          |          |          |          |  Yes  |
|  6 |               growth_rate | -0.114   | 0.0602   |          |          |          |          |       |
|  7 | par binsize co_DLA_z_0_10 | 4        | 0.1      |          |          |          |          |  Yes  |
|  8 |          par_sigma_smooth | 3        | 0.4      |          |          |          |          |  Yes  |
|  9 | per binsize co_DLA_z_0_10 | 4        | 0.1      |          |          |          |          |  Yes  |
| 10 |          per_sigma_smooth | 3        | 0.4      |          |          |          |          |  Yes  |
| 11 |               sigmaNL_par | 6.37     | 0.1      |          |          |          |          |  Yes  |
| 12 |               sigmaNL_per | 3.24     | 0        |          |          |          |          |  Yes  |
| 13 |    sigma_velo_lorentz_DLA | 0        | 0.1      |          |          |          |          |  Yes  |
------------------------------------------------------------------------------------------------------------
```

![auto_DLA_wedges](https://user-images.githubusercontent.com/3166436/54637850-3abf5400-4a4f-11e9-9aae-24a5b21a4024.png)

![2d_DLA_autoCorr](https://user-images.githubusercontent.com/3166436/54637851-3abf5400-4a4f-11e9-8a74-1cd17907a83e.png)

**Comment by TEtourneau** [comment]
Indeed. It's my fault, I used c in m/s instead of km/s to compute dz.
Do you want me to reproduce the DLA catalog with the correct RSD ?

**Comment by londumas** [comment]
Yes, let's reproduce only this catalog to test.

Le mer. 20 mars 2019 à 03:16, TEtourneau <notifications@github.com> a
écrit :

**Comment by TEtourneau** [comment]
I renamed all the dla files of version v4.2 with and "_old" at the end:
master_DLA.fits to master_DLA.fits_old

I sent the job to cori nodes, but it's still in the queue.
I'll let you know when it's done

**Comment by londumas** [comment]
@TEtourneau, thanks for debugging so quickly. You will have to make sure to correct it also in the transmission files for the next production.

**Comment by TEtourneau** [comment]
Actually I sent the production of the DLA catalogs as well as the transmission files (the production of transmission files is fast).
Just be careful that the transmission files will be rewritten in the next few hours (depending on when the job starts)

**Comment by londumas** [comment]
@TEtourneau, perfect.

**Comment by TEtourneau** [comment]
The new DLA master files have been generated. As well as the transmission files.
The RSD should be ok now.

**Comment by londumas** [comment]
@TEtourneau, ok, I am having a look now.

**Comment by londumas** [comment]
@TEtourneau, it looks better but it is still noisy and still quite spherical.
Is it possible to have more stat? To be sure.

![auto_DLA_2d](https://user-images.githubusercontent.com/3166436/54703644-ccd26580-4afe-11e9-9fde-c0a5c0b0c089.png)

![auto_DLA](https://user-images.githubusercontent.com/3166436/54703645-cd6afc00-4afe-11e9-870a-00d447b0fe8c.png)


```
------------------------------------------------------------------------------------------------------------
| No |           Name            |  Value   | Sym. Err |   Err-   |   Err+   | Limit-   | Limit+   | Fixed |
------------------------------------------------------------------------------------------------------------
|  0 |                 alpha_DLA | 1.44     | 0        |          |          |          |          |  Yes  |
|  1 |                        ap | 0.949    | 0.138    |          |          | 0.5      | 1.5      |       |
|  2 |                        at | 0.996    | 0.073    |          |          | 0.5      | 1.5      |       |
|  3 |                   bao_amp | 1        | 0        |          |          |          |          |  Yes  |
|  4 |                  beta_DLA | 0.14     | 0.0575   |          |          |          |          |       |
|  5 |              bias_eta_DLA | 1        | 0        |          |          |          |          |  Yes  |
|  6 |               growth_rate | 0.469    | 0.179    |          |          |          |          |       |
|  7 | par binsize co_DLA_z_0_10 | 4        | 0.1      |          |          |          |          |  Yes  |
|  8 |          par_sigma_smooth | 3        | 0.4      |          |          |          |          |  Yes  |
|  9 | per binsize co_DLA_z_0_10 | 4        | 0.1      |          |          |          |          |  Yes  |
| 10 |          per_sigma_smooth | 3        | 0.4      |          |          |          |          |  Yes  |
| 11 |               sigmaNL_par | 6.37     | 0.1      |          |          |          |          |  Yes  |
| 12 |               sigmaNL_per | 3.24     | 0        |          |          |          |          |  Yes  |
| 13 |    sigma_velo_lorentz_DLA | 0        | 0.1      |          |          |          |          |  Yes  |
------------------------------------------------------------------------------------------------------------
```

**Comment by londumas** [comment]
I subsample the random DLAs that way:
```
nbData = 279510
nbRandoms = 2*nbData

### Data
h = fitsio.FITS(mock['mock_base']+'/master_DLA.fits')
data = {}
for k in ['RA','DEC']:
    data[k] = h['DLACAT'][k][:]
data['Z'] = h['DLACAT']['Z_DLA_RSD'][:]
for k in ['THING_ID','PLATE','MJD','FIBERID']:
    data[k] = h['DLACAT']['MOCKID'][:]
h.close()
phi = data['RA']*sp.pi/180.
th = sp.pi/2.-data['DEC']*sp.pi/180.
pix = healpy.ang2pix(nside,th,phi)
data['PIX'] = pix
print(data['RA'].size)

### Randoms
h = fitsio.FITS(mock['mock_base']+'/master_DLA_randoms.fits')
rand = {}
for k in ['RA','DEC','Z']:
    rand[k] = h[1][k][:]
for k in ['THING_ID','PLATE','MJD','FIBERID']:
    rand[k] = h[1]['MOCKID'][:]
h.close()
phi = rand['RA']*sp.pi/180.
th = sp.pi/2.-rand['DEC']*sp.pi/180.
pix = healpy.ang2pix(nside,th,phi)
rand['PIX'] = pix

### Same HEALpix
w = sp.in1d(data['PIX'],rand['PIX'])
print((~w).sum())
for k,v in data.items():
    v = v[w]
w = sp.in1d(rand['PIX'],data['PIX'])
print((~w).sum())
for k,v in rand.items():
    v = v[w]

### Save data
print(data['RA'].size)
assert nbData<=data['RA'].size
w = sp.random.choice(sp.arange(data['RA'].size), size=nbData, replace=False)
out = fitsio.FITS(mock['picca']+'/Catalogs/DLA_D_'+str(nbData)+'.fits','rw',clobber=True)
cols = [ v[w] for k,v in data.items() if k not in ['PIX'] ]
names = [ k for k in data.keys() if k not in ['PIX'] ]
out.write(cols,names=names)
out.close()
    
### Save randoms
assert nbRandoms<=rand['RA'].size
w = sp.random.choice(sp.arange(rand['RA'].size), size=nbRandoms, replace=False)
out = fitsio.FITS(mock['picca']+'/Catalogs/DLA_R_'+str(nbRandoms)+'.fits','rw',clobber=True)
cols = [ v[w] for k,v in rand.items() if k not in ['PIX'] ]
names = [ k for k in rand.keys() if k not in ['PIX'] ]
out.write(cols,names=names)
out.close()
```

and I compute the correlations that way:
```
for zinterval in zint:
    zmin = zinterval.split(':')[0]
    zmax = zinterval.split(':')[1]

    if not os.path.isdir(mock['picca']+'/Correlations/coDLA_z_{}_{}/'.format(zmin,zmax)):
        os.mkdir(mock['picca']+'/Correlations/coDLA_z_{}_{}/'.format(zmin,zmax))

    cmd = ' srun --time 30 --qos debug -C haswell picca_co.py'
    cmd += ' --out '+mock['picca']+'/Correlations/coDLA_z_{}_{}/coDLA_DD_z_{}_{}.fits.gz'.format(zmin,zmax,zmin,zmax)
    cmd += ' --drq '+mock['picca']+'/Catalogs/DLA_D_'+str(nbData)+'.fits'
    cmd += ' --z-cut-min '+str(zmin)
    cmd += ' --z-cut-max '+str(zmax)
    cmd += ' --type-corr DD ;'
    print(cmd)
    print()

    cmd += ' srun --time 30 --qos debug -C haswell picca_co.py'
    cmd += ' --out '+mock['picca']+'/Correlations/coDLA_z_{}_{}/coDLA_RR_z_{}_{}.fits.gz'.format(zmin,zmax,zmin,zmax)
    cmd += ' --drq '+mock['picca']+'/Catalogs/DLA_R_'+str(nbRandoms)+'.fits'
    cmd += ' --z-cut-min '+str(zmin)
    cmd += ' --z-cut-max '+str(zmax)
    cmd += ' --type-corr RR ;'
    print(cmd)
    print()

    cmd += ' srun --time 30 --qos debug -C haswell picca_co.py'
    cmd += ' --out '+mock['picca']+'/Correlations/coDLA_z_{}_{}/coDLA_DR_z_{}_{}.fits.gz'.format(zmin,zmax,zmin,zmax)
    cmd += ' --drq '+mock['picca']+'/Catalogs/DLA_D_'+str(nbData)+'.fits'
    cmd += ' --drq2 '+mock['picca']+'/Catalogs/DLA_R_'+str(nbRandoms)+'.fits'
    cmd += ' --z-cut-min '+str(zmin)
    cmd += ' --z-cut-max '+str(zmax)
    cmd += ' --type-corr DR ;'
    print(cmd)
    print()

    cmd += ' srun --time 30 --qos debug -C haswell picca_co.py'
    cmd += ' --out '+mock['picca']+'/Correlations/coDLA_z_{}_{}/coDLA_RD_z_{}_{}.fits.gz'.format(zmin,zmax,zmin,zmax)
    cmd += ' --drq '+mock['picca']+'/Catalogs/DLA_R_'+str(nbRandoms)+'.fits'
    cmd += ' --drq2 '+mock['picca']+'/Catalogs/DLA_D_'+str(nbData)+'.fits'
    cmd += ' --z-cut-min '+str(zmin)
    cmd += ' --z-cut-max '+str(zmax)
    cmd += ' --type-corr RD ;'
    print(cmd)
    print()

    cmd += ' srun --time 30 --qos debug -C haswell picca_export_co.py'
    cmd += ' --out '+mock['picca']+'/Correlations/coDLA_z_{}_{}/coDLA_z_{}_{}-exp.fits.gz'.format(zmin,zmax,zmin,zmax)
    cmd += ' --DD-file '+mock['picca']+'/Correlations/coDLA_z_{}_{}/coDLA_DD_z_{}_{}.fits.gz'.format(zmin,zmax,zmin,zmax)
    cmd += ' --RR-file '+mock['picca']+'/Correlations/coDLA_z_{}_{}/coDLA_RR_z_{}_{}.fits.gz'.format(zmin,zmax,zmin,zmax)
    cmd += ' --DR-file '+mock['picca']+'/Correlations/coDLA_z_{}_{}/coDLA_DR_z_{}_{}.fits.gz'.format(zmin,zmax,zmin,zmax)
    cmd += ' --RD-file '+mock['picca']+'/Correlations/coDLA_z_{}_{}/coDLA_RD_z_{}_{}.fits.gz'.format(zmin,zmax,zmin,zmax)
    print(cmd)
    print()
```

**Comment by londumas** [comment]
The status of the ticket is that, the bias of DLA is perfect, the growth-rate seem to low.
It does no seem to be statistical since the Delta-chi2 is of order 60 with the fiducial cosmology value.
Could it be an effect of the mock? What is the difference in implementation between DLA and QSOs?
```
beta(z=2.28) = 0.184 +/- 0.032
f(z=2.28) = 0.409 +/- 0.066
b_DLA(z=2.28) = 2.22
```
![bias_DLA](https://user-images.githubusercontent.com/3166436/55269546-4e8e6580-525a-11e9-8d64-c0cf67032241.png)
![2d_DLA](https://user-images.githubusercontent.com/3166436/55269576-cceb0780-525a-11e9-9122-551ca3f4dd95.png)
![wedge_DLA](https://user-images.githubusercontent.com/3166436/55269577-cceb0780-525a-11e9-934d-e4c8d109d821.png)

**Comment by londumas** [comment]
@TEtourneau, do you have some new results on that? If not, if you want I can look at the 10 new boxes and see how it is across all of them. We will get a better picture of this. Or if you prefer to do it, no problem.

**Comment by TEtourneau** [comment]
I don't remember exactly, but I think we fixed the issue of f beeing too low.
If you have some time, please go ahead. I think you'll be way more faster than me.

Just tell Julianna that you're looking at this, to avoid having 2 people doing the same thing ?
Thanks

**Comment by londumas** [comment]
@TEtourneau, I am going to look at the auto correlation of DLA, it is not on her plan yet. Perfect, I will have a look then.

**Comment by londumas** [comment]
@TEtourneau, I computed the auto-correlation of DLA across the 10 boxes of v4.4 and everything looks ok. Do you have the value of the input bias or beta DLA? Did you input a redshift evolution?
See the following plots and best fit results for the stack of 10 boxes.
Once I have the information about the bias or beta DLA, we can close this ticket.
Thanks for all the work @TEtourneau and @jmarclegoff et al.
```
ap = 1.008 +/- 0.093
at = 0.960 +/- 0.047
beta(z=2.26) = 0.390 +/- 0.028
f(z=2.26) = 0.865 +/- 0.050
b_DLA(z=2.26) = 2.220
```
![stack_dla](https://user-images.githubusercontent.com/3166436/57153113-ad338b80-6d92-11e9-8c55-2c11a5054ba9.png)

![stack_DLA_wedge](https://user-images.githubusercontent.com/3166436/57153112-ad338b80-6d92-11e9-8670-4e59b9d6726c.png)

![growth_rate_DLA](https://user-images.githubusercontent.com/3166436/57153114-ad338b80-6d92-11e9-9291-6f7cddc523c4.png)

![auto_DLA_2d](https://user-images.githubusercontent.com/3166436/57153400-73af5000-6d93-11e9-96e9-b486e1e1160a.png)

![auto_DLA_2d_power_1](https://user-images.githubusercontent.com/3166436/57153399-7316b980-6d93-11e9-91eb-05f8d3966fd0.png)

[edit] adding the plots in 1d for xi and r*xi

**Comment by TEtourneau** [comment]
The input bias is 2, and there is no redshift evolution.
For the beta, there is no input. Velocities are derived from :
v_k = i k/k^2 f a H delta_k
so I guess, if there is no bug, we should recover f of the cosmology.

**Comment by londumas** [comment]
Is it exactly 2 ? Yes we can close the ticket, it is fixed. Thanks for all
the work.

**Comment by londumas** [comment]
@TEtourneau, do you store the value of the input DLA bias somewhere? It should be store either in a fits header or a config file.

**Comment by londumas** [comment]
Closing, because fixed.
