### ISSUE TITLE
Different in low z tail between mock DLA and mock random DLA

### ISSUE THREAD

**Issue by londumas** [igmhub/SaclayMocks#8]
The low redshift tail looks different between mock DLA and mock random DLA.
It can be low number statistics.

![low_tail_DLA_z_distrib](https://user-images.githubusercontent.com/3166436/54294039-8f0d9400-4576-11e9-9f4c-e15fcc841c6f.png)

![high_tail_DLA_z_distrib](https://user-images.githubusercontent.com/3166436/54294040-8fa62a80-4576-11e9-9f54-41e11e32a42f.png)

![DLA_z_distrib](https://user-images.githubusercontent.com/3166436/54294041-8fa62a80-4576-11e9-8094-0464e0761260.png)

**Comment by TEtourneau** [comment]
I removed the random part in the determination of the redshift of randoms:
from 
`z_rnd = np.random.choice(zvec,size=ntot)+0.0025*np.random.normal(size=ntot)` 
to
`z_rnd = np.random.choice(zvec,size=ntot)` 

The low z tail is now the same:
![image](https://user-images.githubusercontent.com/36950825/54442958-eca10c80-473f-11e9-9d9a-e95a5121915a.png)
![image](https://user-images.githubusercontent.com/36950825/54442964-ef036680-473f-11e9-98ca-12ce5ace41f5.png)

**Comment by londumas** [comment]
@TEtourneau, looks good.

**Comment by londumas** [comment]
Fixed in v4.2.

![low_z_tail](https://user-images.githubusercontent.com/3166436/54628031-48b6aa00-4a3a-11e9-8c6b-862c46c79b91.png)

![high_z_tail](https://user-images.githubusercontent.com/3166436/54628030-48b6aa00-4a3a-11e9-82a0-1b404345759a.png)
